# Generated by Django 4.2.16 on 2024-12-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses_images/')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
