# Generated by Django 5.1.4 on 2024-12-20 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_authuser_enrollments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthUser',
        ),
    ]
