# Generated by Django 4.2.16 on 2024-12-22 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_authuser'),
        ('home', '0006_create_courses_table'),
    ]

    operations = [
    ]
