# Generated by Django 4.2.16 on 2024-12-22 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_merge_0005_authuser_0006_create_courses_table'),
        ('home', '0008_create_enrollments_table'),
    ]

    operations = [
    ]
